# Site settings
title: 페이퍼 세상에 살아요...
header-img: img/home-bg.jpg
email: kimpaper@gmail.com
description: "나만 보면 된다."
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: SBootstrap
github_username:  kimpaper
facebook_username:  seretude

# Build settings
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]
