# Site settings
title: 페이퍼 세상에 살아요...
header-img: img/home-bg.jpg
email: kimpaper@gmail.com
description: "나만 보면 된다."
baseurl: "/kimpaper"
#url: "http://yourdomain.com"
#twitter_username: SBootstrap
github_username:  kimpaper
facebook_username:  seretude

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
