# Site settings
title: 페이퍼 세상 살아요...
email: kimpaper@gmail.com
description: > # 나만 보면 된다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kimpaper.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  kimpaper

# Build settings
markdown: kramdown
